services:
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend
      target: runner
    ports:
      - "5173:80"